accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
]

control_panel/urls.py
# main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('run-pokebot/', views.run_pokebot, name='run_pokebot'),
]

pokewars/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('control_panel.urls')),
    path('accounts/', include('accounts.urls')),
]

accounts/models.py
from django.db import models

# Create your models here.

control_panel/models.py
from django.db import models

# Create your models here.

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages

# Create your views here.
def login_view(request):
    if request.method == 'POST':
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('/')
        else:
            messages.error(request, 'Wrong username or password.')

    return render(request, 'accounts/login.html')


def logout_view(request):
    logout(request)
    return redirect('/')

control_panel/views.py
# main_app/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
import subprocess
from django.http import JsonResponse

selenium_process = None

@login_required
def home(request):
    return render(request, 'control_panel/home.html')

@login_required
def run_pokebot(request):
    global bot_process

    try:
        if request.session.get('bot_running', False) and bot_process is not None:
            # Stop the bot if it is urnning
            bot_process.terminate()
            bot_process = None
            request.session['bot_running'] = False
            return JsonResponse({'status': 'stopped'})
        else:
            # Run the bot
            print("Running the pokebot...")

            bot_process = subprocess.run(
                ['python3', '/home/ubuntu/django/selenium/pokebot.py'],
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE
            )

            # Read the output
            stdout, stderr = bot_process.communicate()

            if stdout:
                print(f"Bot output: {stdout.decode('utf-8')}")
            if stderr:
                print(f"Bot error: {stderr.decode('utf-8')}")

            request.session['bot_running'] = True
            return JsonResponse({'status': 'started'})
    except Exception as e:
        print("Error while running the pokebot:", e)
        print(traceback.format_exc())
        return JsonResponse({'status': 'error', 'message': str(e)})

accounts/templates/accounts/login.html
<!-- templates/accounts/login.html -->
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <link rel="stylesheet" type="text/css" href="{% static 'accounts/style.css' %}">
  <title>Control Panel Login</title>
</head>
<body>
  <div id="container">
    <div id="login_bg">
      <div id="login_form">
        <p id="login_text">Log In</p>
        <form id="input_fields" action="{% url 'accounts:login' %}" method="POST">
            {% csrf_token %}
            <input class="input_field" type="text" name="username" id="username" placeholder="Username" required>
            <input class="input_field" type="password" name="password" id="password" placeholder="Password" required>
            <button id="submit_button" type="submit">START</button>
        </form>
      </div>
    </div>
  </div>
</body>
</html>

control_panel/templates/control_panel/home.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Control Panel</title>
    <link rel="stylesheet" type="text/css" href="{% static 'control_panel/home.css' %}">
    <script>
        function toggleBot() {
            fetch('/run-pokebot/', {
                method: 'GET',
            })
            .then(response => response.json())
            .then(data => {
                if (data.status === 'started') {
                    document.getElementById('pokebot-status').innerText = "PokeBot jest uruchomiony";
                } else if (data.status === 'stopped') {
                    document.getElementById('pokebot-status').innerText = "PokeBot został zatrzymany";
                }
            });
        }
    </script>
</head>
<body>
    <div id="wrapper">
        <div id="main_app">
            <a href="{% url 'accounts:logout' %}"><button type="submit" id="logout_button">Logout</button></a>
            <p id="pokebot-status">PokeBot nie jest uruchomiony</p>
            <form method="POST" action="{% url 'run_pokebot' %}">
                {% csrf_token %}
                <input type="text">
                <input type="text">
                <input type="text" name="" id="">
                <button type="submit">Run PokeBot</button>
            </form>
        </div>
    </div>
</body>
</html>